[fade]
start = 1
limit = 100
spotify_volume = 80
step = 1
seconds = 300
force = false

[database]
provider = "sqlite"
filename = "$HOME/.cache/alarm/db.sqlite"
create_db = true

[spotify.auth]
email = 'alin.p32@gmail.com'
username = 'alin.p32'

[spotify.player]
device = 'HomePod'
speaker = ''

[recommendations]
artist_limit = 3
use_related = false

min_acousticness = 0.3
max_speechiness = 0.5
min_valence = 0.4

    [recommendations.features_order]
    loudness = 1
    energy = 1
    instrumentalness = -1
    speechiness = 1
    valence = -1

[location]
name = "Iași"